[package]
name = "yew-nested-router-example"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
yew = { version = "0.20", features = ["csr"] }
yew-nested-router = { path = "../.." }

wasm-bindgen = "0.2.83"
wasm-logger = "0.2"
