[package]
name = "yew-nested-router-example"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
gloo-utils = "0.2"
yew = { version = "0.22", features = ["csr"] }
yew-nested-router = { path = "../.." }

wasm-bindgen = "0.2.83"
wasm-logger = "0.2"

[workspace]
